--- !Ups

INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Faculty of Arts", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Business and Economic Sciences", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Education", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Engineering, the Built Environment and IT", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Health Sciences", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Law", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("Science", "");
INSERT INTO rech_system.Faculty(faculty_name, faculty_info) VALUES ("All", "");

INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Agriculture", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Game Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Agricultural Management (George campus)", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Applied Language Studies", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Architectural Technology & Interior Design", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Architecture", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Biochemistry and Microbiology", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Botany", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Building and Human Settlement Development", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Business Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Ceramics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Chemistry", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Civil Engineering", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Computing Sciences", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Construction Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Criminal and Procedural Law", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Development Studies", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Dietetics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Drawing", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Economics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Electrical Engineering", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Emergency Medical Care", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Environmental Health", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Fashion & Textile Design", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Forestry (George campus)", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Game Management (Port Elizabeth, Addo)", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Game Ranch Management (George campus)", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Geosciences", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Graphic Design", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Human Movement Science", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Human Resources Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Industrial and Organisational Psychology", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Industrial Engineering", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Information Technology", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Media and Communication", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Language & Literature", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Logistics Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Management and Entrepreneurship", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Marketing Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Mathematics and Applied Mathematics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Mechanical Engineering", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Mechatronics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Medical Laboratory Sciences", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Mercantile Law", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Music", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Nature Conservation (George campus)", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Nursing Science", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Ocean Sciences", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Painting", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Pharmacy", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Photography", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Physics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Political and Conflict Studies", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Printmaking", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Private Law", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Psychology", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Public Law", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Public Management and Leadership", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Quantity Surveying", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Radiography", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Sculpture", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Social Development Professions", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Sociology and Anthropology", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Statistics", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Textile Science", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Tourism Management", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Visual Arts", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Wood Technology (George campus)", "All");
INSERT INTO rech_system.Department(department_name, faculty_name) VALUES ("Zoology", "All");

--- !Downs